---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    run: demo
    app: demo
spec:
  containers:
  - name: app-container
    image: gcr.io/week5-434112/demo:v2.0.0
    ports:
    - containerPort: 8000
    env:
    - name: USERNAME1
      valueFrom:
        secretKeyRef:
          name: secret1
          key: username1
    - name: USERNAME2
      valueFrom:
        secretKeyRef:
          name: secret2
          key: username2
