apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    run: demo
    app: demo
spec:
  containers:
  - name: app-container
    image: gcr.io/week5-434112/demo:v2.0.0
    ports:
    - containerPort: 8000
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
