---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    run: demo
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/week5-434112/demo:v2.0.0
    ports:
    - containerPort: 8000
      name: http